travel/chatapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^chat/$', views.app, name='twilio'),
    url(r'^token', views.token, name='token'),
]

travel/thirdauth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', views.authentication, name='authentication'),
    url(r'^logout/$', views.logout_self, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.authentication, name='authentication'),
]

#LOGIN_URL = 'login'
#LOGOUT_URL = 'logout'
#LOGIN_REDIRECT_URL = 'home'

travel/travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('worldmap.urls', namespace='worldmap')),
    url(r'', include('thirdauth.urls', namespace='thirdauth')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'', include('reservations.urls', namespace='reservations')),
    url(r'', include('chatapp.urls', namespace='chatapp')),
]
LOGIN_REDIRECT_URL = 'home'

travel/worldmap/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    url(r'^planner/$', views.plannerGetStarted, name='getStarted'),
    url(r'^accounts/profile/$', views.home, name='profile'),
    url(r'^location_json/', views.LocationText.as_view()),
    url(r'^planner/location_information/$', views.locationInformation, name='location'),
    url(r'^planner/location_LngLat/$', views.getLngLat, name='lnglat'),
    url(r'^planner/location_AirportCode/$', views.getAirportCode, name='airportCode'),
    url(r'^planner/locations/$', views.getLocations, name='locations'),
    url(r'^planner/locationsByType/$', views.getLocationsByType, name='locationsByType'),
    url(r'^planner/location/$', views.getLocation, name='getLocation'),
    url(r'^planner/search_update/$', views.searchUpdate, name='searchUpdate'),
    url(r'^sendsms/$', views.send_twilio_message, name='send_sms'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

travel/worldmap/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
import decimal

from django import forms
from django.core.validators import MinLengthValidator
from django.core.validators import MaxLengthValidator
from django.core.validators import RegexValidator
from django.utils import timezone
# Create your models here.


class SendSMS(models.Model):
    to_number = models.CharField(max_length=30)
    from_number = models.CharField(max_length=30)
    body = models.CharField(max_length=500, default="", blank=True)
    sms_sid = models.CharField(max_length=34, default="", blank=True)
    account_sid = models.CharField(max_length=34, default="", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    delivered_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, default="", blank=True)

class Region (models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=500, null=False)

    def __str__(self):
        return self.name

class Type (models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=500, null=False)

    def __str__(self):
        return self.name

class Location (models.Model):
    name = models.CharField(max_length=200, null=False)
    lng = models.DecimalField(max_digits=50, decimal_places=7, null=False)
    lat = models.DecimalField(max_digits=50, decimal_places=7, null=False)
    description = models.CharField(max_length=500, null=False)
    type = models.ForeignKey(Type, related_name='region')
    rank = models.IntegerField(null=True)
    airportCode = models.CharField(max_length=10, null=False)
    region = models.ForeignKey(Region, related_name='region')

    def __str__(self):
        return self.name

    def __iter__(self):
        return [self.name,
                self.lng,
                self.lat,
                self.description,
                self.type,
                self.rank,
                self.airportCode,
                self.region]

    def getNameLngLatDescription(self):
        return [{"name": str(self.name), "lng": str(self.lng), "lat": str(self.lat), "description": str(self.description), "rank": str(self.rank)}]

class VisitorInterest (models.Model):
    user = models.CharField(max_length=200, null=False)
    location = models.CharField(max_length=200, null=False)
    searches = models.IntegerField(null=True)


    def __str__(self):
        return self.user + " " + self.location + ": " + str(self.searches)

travel/worldmap/forms.py
from django import forms

from .models import SendSMS

class SendSMSForm(forms.Form):
    to_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'to_number', 'placeholder': '+14026861203'}))
    body = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'body', 'placeholder': 'Hi FLo!'}))

class FlightForm(forms.Form):
    origin = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'origin', 'placeholder': 'OMA'}))
    destination = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'destination', 'placeholder': 'LAX'}))
    startdate = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'startdate', 'placeholder': 'YYYY-MM-DD'}))


class HotelForm(forms.Form):
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'location', 'placeholder': 'LAX'}))
    check_in = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'check_in', 'placeholder': 'YYYY-MM-DD'}))
    check_out = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'check_out', 'placeholder': 'YYYY-MM-DD'}))


class ZomatoForm(forms.Form):
    locationcity = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'keyword', 'placeholder': 'Pizza'}))
    lngRestaurant = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'lngRestaurant', 'placeholder': 'Long'}))
    latRestaurant = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'latRestaurant', 'placeholder': 'Lat'}))

travel/worldmap/views.py
from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from . import forms
from worldmap.models import Region, Type, Location, VisitorInterest
from django.core import serializers
from django.conf import settings
from twilio.rest import Client

#For the wikipedia entries
import wikipediaapi
import twilio.rest

#For the rest web services
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import LocationDescriptionSerializer, LocationSerializer


def home(request):
   return render(request, 'worldmap/home.html',
                 {'worldmap': home})

def getLocationText(locationName):
    wiki_wiki = wikipediaapi.Wikipedia('en')
    page_py = wiki_wiki.page(locationName)
    return page_py.summary[0:800]

@login_required
def plannerGetStarted(request):
    form = forms.FlightForm()
    hotel_form = forms.HotelForm()
    zomato_form = forms.ZomatoForm()
    sms_form = forms.SendSMSForm()
    return render(request, 'worldmap/planner.html', {'hotel_form': hotel_form, 'form': form, 'zomato_form': zomato_form, 'sms_form': sms_form})


#Functions to get json strings
class LocationText(APIView):

    def get(self,request):
        text_json = LocationText('Denver')
        data = [{"text" : text_json}]
        serializer = LocationDescriptionSerializer(data, many=True)
        return Response(serializer.data)

def locationInformation(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            location = request.POST['location']
            text = getLocationText(location)
            return HttpResponse(text) # if everything is OK
    # nothing went well
    return HttpResponse('FAIL!!!!!')

#Function to grab lng and lat for a specific location
def getLngLat(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            location = request.POST['location']
            locObject = Location.objects.get(name=location)
            data = [{"lng": str(locObject.lng), "lat": str(locObject.lat)}]
            return HttpResponse(json.dumps(data))

    return HttpResponse('FAIL!!!!!')

#Function to grab the airportCode for a specific location
def getAirportCode(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            location = request.POST['location']
            locObject = Location.objects.get(name=location)
            return HttpResponse(str(locObject.airportCode))

    return HttpResponse('FAIL!!!!!')

#Function to grab all the information about the locations
def getLocations(request):
    if request.method == 'POST':
        locations = Location.objects.all()
        serializer = LocationSerializer(locations, many=True)
        return HttpResponse(json.dumps(serializer.data))

    return HttpResponse('FAIL!!!!!')

#Function to grab all the information about the locations
def getLocation(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            location = request.POST['location']
            location = Location.objects.get(name=location).getNameLngLatDescription()
            return HttpResponse(json.dumps(location))
            #return HttpResponse('test')

    return HttpResponse('FAIL!!!!!')

#Function to grab the airportCode for a specific location
def getLocationsByType(request):
    if request.method == 'POST':
        if 'type' in request.POST:
            type = request.POST['type']
            selectedType = Type.objects.get(name=type)
            locations = Location.objects.filter(type=selectedType)
            serializer = LocationSerializer(locations, many=True)
            return HttpResponse(json.dumps(serializer.data))

    return HttpResponse('FAIL!!!!!')

#Function to update the VisitorInterest table
def searchUpdate(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            location = request.POST['location']
            username = request.user.username
            if VisitorInterest.objects.filter(user=username).exists():
                if VisitorInterest.objects.filter(user=username).filter(location=location).exists():
                    object = VisitorInterest.objects.filter(user=username).get(location=location)
                    object.searches = object.searches + 1
                    object.save()
                else:
                    entry = VisitorInterest(user=username, location=location, searches=1)
                    entry.save()
            else:
                entry =  VisitorInterest(user=username, location=location, searches= 1)
                entry.save()
            return HttpResponse('')

    print('FAIL!!!!!')


#function for writing a sms
def send_twilio_message(request):
    #sid = "AC77010b7d86d3a356f80667e6d790c128"
    #token = "b0fd38a04a4e570bb6d3f35e570a67d4"
    client = Client(settings.TWILIO_ACCT_SID, settings.TWILIO_AUTH_TOKEN)
    #client = Client("AC77010b7d86d3a356f80667e6d790c128","b0fd38a04a4e570bb6d3f35e570a67d4")
    # if request.method == 'POST':
    #     sms_form = SMSForm(request.POST)
    #     if sms_form.is_valid():
    #         data2 = zomato_form.cleaned_data
    #         resp2 = p.search(q=data2['locationcity'], lat='41.277072', lon='-96.060682', radius='25000', count='3',
    #                          sort='rating')
    client.messages.create(
        body=request.POST['body'],
        to=request.POST['to_number'],
        #to='+14026861203',
        from_='+14028108945'  #settings.TWILIO_PHONE_NUMBER
    )

    print(request.POST['to_number'])
    return HttpResponse('');

travel/worldmap/templates/worldmap/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>


    <title>Byzantium-Travel</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'css/images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'css/images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'css/images/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'css/images/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'css/images/favicon/safari-pinned-tab.svg' %}" color="#ff0000">
  <link rel="shortcut icon" href="{% static 'css/images/favicon/favicon.ico' %}">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-config" content="{% static 'css/images/favicon/browserconfig.xml' %}">
  <meta name="theme-color" content="#ffffff">

    <!--internet css files -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!--static css files -->
    <link rel="stylesheet" href="{% static 'twilio/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/worldmap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">
    <link rel="stylesheet" href="{% static 'css/animations.scss' %}">
    <link rel="stylesheet" href="{% static 'css/styling.css' %}">



    <!--internet js files -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!--APIs -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcUbUzlOE1t6OIbdZpQx7k1IQgSfUYhmA"
    async defer></script>

    <!--static js files -->
    <script type="text/javascript" src="{% static 'js/jquery.smoothscroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/js.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/worldmap.js' %}"></script>
    <script type="text/javascript" src="{% static 'images/galleryAll/jbcore/juicebox.js' %}"></script>
    <script>
            $(function() {
            $('html').smoothScroll(500);
            });
    </script>

</head>
<!--
Navbar by https://github.com/alphadsy - free to use
-->

  <nav class="navbar navbar-default navbar-doublerow navbar-trans navbar-fixed-top">
  <!-- top nav -->
  <nav class="navbar navbar-top hidden-xs">
    <div class="container">
      <!-- left nav top -->
      <ul class="nav navbar-nav pull-left">
        <li><a href="#"><span class="glyphicon glyphicon-thumbs-up text-white"></span></a></li>
        <li><a href="#"><span class="glyphicon glyphicon-globe text-white"></span></a></li>
        <li><a href="#"><span class="glyphicon glyphicon-pushpin text-white"></span></a></li>
        <li><a href="#"><span class="text-white">QUESTIONS? CALL: <b>+40288888888</b></span></a></li>
      </ul>
      <!-- right nav top -->
      <ul class="nav navbar-nav pull-right">
        <li><a href="" class="text-white">About Us</a></li>
        <li><a href="" class="text-white">Contact Us</a></li>
      </ul>
    </div>
    <div class="dividline light-grey"></div>
  </nav>
  <!-- down nav -->
  <nav class="navbar navbar-down">
    <div class="container">
      <div class="flex-container">
        <div class="navbar-header flex-item">
          <div class="navbar-brand" href="https://Byzantium-Travel.herokuapp.com">BYZANTIUM</div>
        </div>
        <ul class="nav navbar-nav flex-item hidden-xs">
          <li><a href="{% url 'worldmap:home' %}">Features</a></li>
          <li><a href="{% url 'worldmap:getStarted' %}">Planner</a></li>
          <li><a href="{% url 'thirdauth:authentication' %}">Login</a></li>
          <li><a href="{% url 'thirdauth:logout' %}">Logout</a></li>
          <!--<li><a href="">TheTeam</a></li> -->
        </ul>
        <ul class="nav navbar-nav flex-item hidden-xs pull-right">
          <li><a href="#" class=""></a></li>
        </ul>
        <!-- dropdown only moblie -->
          <div class="dropdown visible-xs pull-right">
            <button class="btn btn-default dropdown-toggle " type="button" id="dropdownmenu" data-toggle="dropdown">
              <span class="glyphicon glyphicon-align-justify"></span>
            </button>
            <ul class="dropdown-menu">
              <li><a href="{% url 'worldmap:home' %}">Features</a></li>
              <li><a href="{% url 'worldmap:getStarted' %}">Get Started</a></li>
              <li><a href="{% url 'chatapp:twilio' %}">Start Chat</a></li>
              <li><a href="{% url 'thirdauth:authentication' %}">Login</a></li>
              <li><a href="{% url 'thirdauth:logout' %}">Logout</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Contact us</a></li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </nav>

{% block content %}
{% endblock %}
<footer class="page-footer font-small blue pt-4 mt-4">

    <!--Footer Links-->
    <div class="container-fluid text-center text-md-left">
        <div class="row" id="foot">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Footer Content</h5>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div>
            <!--/.First column-->

            <!--Second column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Home</a>
                    </li>
                    <li>
                        <a href="#!">Planner</a>
                    </li>
                    <li>
                        <a href="#!">Contact</a>
                    </li>
                    <li>
                        <a href="#!">Github Repo</a>
                    </li>
                </ul>
            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright:
        <a href="https://byzantium-travel.herokuapp.com/"> Byzantium-Travel-herokuapp.com </a>
    </div>
    <!--/.Copyright-->

</footer>
    <script>
     // toggle class scroll
$(window).scroll(function() {
    if($(this).scrollTop() > 50)
    {
        $('.navbar-trans').addClass('afterscroll');
    } else
    {
        $('.navbar-trans').removeClass('afterscroll');
    }

});

// demo only
// open link in new tab without ugly target="_blank"
$("a[href^='http']").attr("target", "_blank");

    </script>
</body>
</html>

travel/worldmap/templates/worldmap/home.html
{% extends 'worldmap/base.html' %}
{% load staticfiles %}
{% block content %}
<header>
    <img src="{% static 'css/images/bg-home.jpg' %}" style="width:100%">

</header>
<div class="ontop container">
<div class="row">
  <div class="col-sx-12 text-center">
      <h1>Byzantium Travel</h1>
      <h2>- Find your next adventure</h2>
      <button class="btn btn-danger"><a href="#Features">Read more</a>
    </div>
</div>
</div>
<div class="darkpattern" id="Features">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Reasons to Use Byzantium Travel</h2>
        <br>
        <div class="col-md-6 text-center">
          <h3>Personal Attention<h3>
        </div>
        <div class="col-md-6">
          <p>From your first visit to sharing your travel, you will engage experience travelers who have lived,
              worked and played all over the world. Our travel web portal understands your unique style and
              interests as we design and help you choose your authentic trip.
          </p>
        </div>
        <div class="col-md-6 text-center">
          <h3>Peace of Mind<h3>
        </div>
        <div class="col-md-6">
          <p>Constant research, site visits and attention to detail allows our members to build exciting travel
            adventures. You can have confidence that our members have experienced safe travel, comfort and
            seamless travel.  Byzantium Travel identifies travel locations that are dependability you can trust.
          </p>
        </div>
        <div class="col-md-6 text-center">
          <h3>Tailored to you<h3>
        </div>
        <div class="col-md-6">
          <p>Combine your travel interests and our member recommendations to build an enviable travel
              encounters.  Share you’re your experiences to document your off-the-beaten path locations, local
              culture, wildlife encounters, and private access are our specialties. Byzantium Travel helps you locate
              and arrange travel to ancient sites like Machu Picchu, Angkor Wat and Tikal, or explore urban
              Shanghai or Cape Town. Our webservices help you arrange high-adrenaline adventures in the wilds of
              Patagonia or Costa Rica, we can make your ideal getaway happen.
          </p>
        </div>
        <div class="col-md-6 text-center">
          <h3>Get Inspired<h3>
        </div>
        <div class="col-md-6">
          <p>Our members span the globe, documenting their travel to remote places, and recommend local travel adventures at destination locations
              and even the most remote places. Think Antarctica, Galapagos, Patagonia, the Arctic, or the Amazon are obscure destinations?
              These locations are a few of the locations our members have experienced.  Share your travels with Byzantium Travel members ad
              build your travel portfolio.
          </p>
        </div>
        <div class="text-center">
        <button class="btn btn-danger"><a href="{% url 'worldmap:getStarted' %}">Start Planning</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}